spring:
  application:
    name: apigateway-microservice-ecomm
  profiles:
    active: local   

server:
  port: 8080
  
---
   
spring:
  config.activate.on-profile: local
  cloud:
    gateway:
      routes:
        - id: customer-microservice-ecomm
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
            
        - id: product-microservice-ecomm
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: wishlist-microservice-ecomm
          uri: http://localhost:8083/
          predicates:
            - Path=/wishlist/**
            - Path=/wishlistProduct/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: cart-microservice-ecomm
          uri: http://localhost:8084/
          predicates:
            - Path=/cartitem/**
          filters:
            - name: JWTAuthorizationFilter
            
---

eureka:
  client:
   service-url:
      defaultZone: https://eureka-server-ecommerce.herokuapp.com/eureka

spring:
  config.activate.on-profile: cloud
  cloud:
    gateway:
      routes:
        - id: customer-microservice-ecomm
          uri: http://customer-microservice-ecomm.herokuapp.com/
          predicates:
            - Path=/customers/**
            
        - id: product-microservice-ecomm
          uri: http://product-microservice-ecomm.herokuapp.com/
          predicates:
            - Path=/products/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: wishlist-microservice-ecomm
          uri: http://wishlist-microservice-ecomm.herokuapp.com/
          predicates:
            - Path=/wishlist/**
            - Path=/wishlistProduct/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: cart-microservice-ecomm
          uri: http://cart-microservice-ecomm.herokuapp.com/
          predicates:
            - Path=/cartitem/**
          filters:
            - name: JWTAuthorizationFilter
            
            
