spring:
  application:
    name: apigateway-microservice-ecommerce
  profiles:
    active: local   

server:
  port: 8080
  
eureka:
  instance:
   hostname: localhost
   
---
   
spring:
  config.activate.on-profile: local
  cloud:
    gateway:
      routes:
        - id: customer-microservice-ecommerce
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
            
        - id: product-microservice-ecommerce
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: wishlist-microservice-ecommerce
          uri: http://localhost:8083/
          predicates:
            - Path=/wishlist/**
            - Path=/wishlistProduct/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: cart-microservice-ecommerce
          uri: http://localhost:8084/
          predicates:
            - Path=/cartitem/**
          filters:
            - name: JWTAuthorizationFilter
            
---

spring:
  config.activate.on-profile: cloud
  cloud:
    gateway:
      routes:
        - id: customer-microservice-ecommerce
          uri: http://customer-microservice-ecommerce.herokuapp.com/
          predicates:
            - Path=/customers/**
            
        - id: product-microservice-ecommerce
          uri: http://product-microservice-ecommerce.herokuapp.com/
          predicates:
            - Path=/products/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: wishlist-microservice-ecommerce
          uri: http://wishlist-microservice-ecommerce.herokuapp.com/
          predicates:
            - Path=/wishlist/**
            - Path=/wishlistProduct/**
          filters:
            - name: JWTAuthorizationFilter
            
        - id: cart-microservice-ecommerce
          uri: http://cart-microservice-ecommerce.herokuapp.com/
          predicates:
            - Path=/cartitem/**
          filters:
            - name: JWTAuthorizationFilter
            
            
